### ISSUE TITLE
Publish the code to the forte repository

### ISSUE THREAD

**Issue by cochicde** [MrcJkb/forte_http_comm#1]
Hi. I was just wondering if it would be possible that you push your code to the public repository of forte, so we can later maintain and use it without problems. I'm not sure if there are issues with the license or so

**Comment by mrcjkb** [comment]
Hi.
Sure, I can do that. I am currently on a trip and don't have my laptop with me, but I will look into it when I get back.
I can change the license to match the EPL if necessary.

**Comment by cochicde** [comment]
Thanks! It's really apreciated. Yes, forte can only accept files that have the EPL license. And you need to sign the ECA. I'd say that you could push to the develop branch, even if the new changes make the layer not compilable, we could easily fix this to make it ready.

Here some info on how to contribute to forte:

https://www.eclipse.org/4diac/documentation/html/development/contributeToForte.html

**Comment by mrcjkb** [comment]
I have changed the license, copied the module over to the develop branch and committed to Gerrit :)
I will add a comment in the readme that this repository is no longer maintained.

**Comment by mrcjkb** [comment]
Oops, I forgot to read the "2. Contributing" subsection. So the commit message isn't in line with the Gerrit requirements yet.
I have reverted my commit and opened the following issue in Eclipse: https://bugs.eclipse.org/bugs/show_bug.cgi?id=532020

I will attempt to re-commit with a correct message.

**Comment by mrcjkb** [comment]
Okay, the changes have now been accepted by Gerrit. Let me know when it has been merged to a stable version for FORTE :)
Here's the code review link: https://git.eclipse.org/r/#/c/118683/
